### PR TITLE
Change shebang declaration to avoid shell errors

### PR DESCRIPTION
**Pull request by M0Rf30**
fish says
Failed to execute process './make_openbazaar.sh'. Reason:  
exec: Exec format error  
The file './make_openbazaar.sh' is marked as an executable but could not be run by the operating system. 

bash says;
make_openbazaar.sh: riga 1: #!/bin/sh: File o directory non esistente

### CODE REVIEW

**Comment by hoffmabc** [comment]
why did you close this @M0Rf30 ?

**Comment by M0Rf30** [comment]
Because the little typo error is not fixed as I wish. fish shows this message again

**Comment by hoffmabc** [comment]
sorry I missed something, what's fish?

**Comment by M0Rf30** [comment]
fish is a popular shell for unix environment

**Pull request closed without merging**
